Parse smiles
project-chi/chi-editor pull request #25
Opened 2022-12-13 12:56 UTC by MIZINCHIK

2022-12-13 14:39 UTC, kapkekes requested changes

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/bases/line.py
> +    Parent class for all chemical bonds.
Это краткое описание класса, поэтому содержимое десятой строчки должно идти сразу после тройных кавычек.

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/playground.py
> +        node_to_idx[i] = molIdx
Это абсолютно равносильный код.

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/playground.py
> +    return False
Не забываем про сигнатуры аргументов и возвращаемого значения.

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/toolbar/tools/structure.py
> +        molecule = QGraphicsSvgItem('resources//molecule.svg')
Мне кажется, здесь как-то можно передать содержимое сразу в `QGraphicsSvgItem`, как строку с самим SVG, нужно посмотреть.

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/toolbar/tools/eraser.py
> +
Должна быть одна строчка, а не две.

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/toolbar/tools/bond.py
> +                return
Он здесь не нужен.

2022-12-13 14:39 UTC, kapkekes commented on chi_editor/toolbar/tools/bond.py
> +            return
Тут тоже лишний `return`.

2023-02-04 11:34 UTC, tobaffoon commented on chi_editor/toolbar/tools/arrow.py
> +        super(Canvas, self.canvas).mouseMoveEvent(event)
super() вызывается от холста стрелки, а не от неё самой, так что просто super()  не подойдёт

2023-02-11 09:51 UTC, merged